name: GridBruno
favicon: null
layout_spectrum: 0.2958264590706676
typography_spectrum: 0.7541499063372612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ccb29f'
    - '#8d715f'
    - '#39362f'
    - '#ff0021'
  brandStrength: 0.625
  lightness: 0.7797747780568898
  saturation: 0.2891567423939705
  rhythmicContrast: 0.6621046254877001
purpose: []
